import Foundation

/// Static fitness-knowledge question catalog: 5 questions per
/// category/difficulty combination (3 categories × 3 difficulties × 5 = 45).
enum QuestionBank {
    static let all: [Question] = trainingslehre + ernaehrung + uebungsausfuehrung

    static func questions(for category: QuizCategory, difficulty: Difficulty) -> [Question] {
        all.filter { $0.category == category && $0.difficulty == difficulty }
    }

    private static let trainingslehre: [Question] = [
        // Leicht
        Question(category: .trainingslehre, difficulty: .leicht,
                 text: "Was bedeutet die Abkürzung „1RM“ im Krafttraining?",
                 answers: ["One-Repetition Maximum", "Resting Metabolic Rate", "Recovery Muscle Mass", "Range of Motion"],
                 correctAnswerIndex: 0,
                 explanation: "1RM steht für „One-Repetition Maximum“ und bezeichnet das höchste Gewicht, das bei einer Übung für genau eine Wiederholung bewältigt werden kann."),
        Question(category: .trainingslehre, difficulty: .leicht,
                 text: "Wie oft pro Woche empfiehlt die WHO mindestens muskelkräftigendes Training für Erwachsene?",
                 answers: ["1×", "2×", "4×", "7×"],
                 correctAnswerIndex: 1,
                 explanation: "Die WHO empfiehlt mindestens zwei muskelkräftigende Einheiten pro Woche, die alle großen Muskelgruppen beanspruchen."),
        Question(category: .trainingslehre, difficulty: .leicht,
                 text: "Was versteht man unter „Aufwärmen“ (Warm-up)?",
                 answers: ["Vorbereitende leichte Bewegung vor dem Training", "Ein kurzes Nickerchen direkt vor dem Training", "Intensives Dehnen der Muskulatur nach dem Training", "Eine kalte Dusche unmittelbar vor dem Training"],
                 correctAnswerIndex: 0,
                 explanation: "Aufwärmen bereitet Muskulatur, Gelenke und Kreislauf durch leichte Bewegung auf die kommende Belastung vor und senkt das Verletzungsrisiko."),
        Question(category: .trainingslehre, difficulty: .leicht,
                 text: "Was ist eine „Wiederholung“ (Rep) beim Krafttraining?",
                 answers: ["Eine vollständige Ausführung einer Übung", "Eine Trainingswoche", "Eine Pause zwischen zwei Sätzen", "Ein komplettes Trainingsprogramm"],
                 correctAnswerIndex: 0,
                 explanation: "Eine Wiederholung ist die einmalige, vollständige Ausführung einer Bewegung von der Start- bis zur Endposition und zurück."),
        Question(category: .trainingslehre, difficulty: .leicht,
                 text: "Was bedeutet „Satz“ (Set) beim Krafttraining?",
                 answers: ["Eine Gruppe aufeinanderfolgender Wiederholungen ohne Pause", "Die maximale Gewichtsangabe auf einer Hantel", "Eine komplette Trainingswoche im Kalender", "Der Name eines bestimmten Übungsgeräts"],
                 correctAnswerIndex: 0,
                 explanation: "Ein Satz besteht aus mehreren direkt aufeinanderfolgenden Wiederholungen derselben Übung ohne Pause dazwischen."),
        // Mittel
        Question(category: .trainingslehre, difficulty: .mittel,
                 text: "Was beschreibt das Prinzip der „progressiven Überlastung“?",
                 answers: ["Schrittweise Steigerung des Trainingsreizes zur Anpassung", "Immer dasselbe Gewicht über Monate zu nutzen", "Training bis zur völligen Erschöpfung in jeder Einheit", "Tägliches Training ohne Ruhetage"],
                 correctAnswerIndex: 0,
                 explanation: "Progressive Überlastung bedeutet, den Trainingsreiz – z.B. Gewicht, Wiederholungen oder Volumen – schrittweise zu steigern, damit sich der Körper immer wieder neu anpassen muss."),
        Question(category: .trainingslehre, difficulty: .mittel,
                 text: "Wie lange sollte die Satzpause bei klassischem Hypertrophietraining (Muskelaufbau) typischerweise sein?",
                 answers: ["10–20 Sekunden", "60–90 Sekunden", "5 Minuten", "Keine Pause nötig"],
                 correctAnswerIndex: 1,
                 explanation: "Für klassisches Muskelaufbautraining gelten 60–90 Sekunden Pause oft als guter Kompromiss zwischen ausreichender Erholung und Trainingsdichte."),
        Question(category: .trainingslehre, difficulty: .mittel,
                 text: "Was versteht man unter „Periodisierung“ im Training?",
                 answers: ["Systematische Planung und Variation von Trainingsreizen über die Zeit", "Das genaue Zählen der Wiederholungen innerhalb eines Satzes", "Die feste Reihenfolge der Übungen innerhalb einer Einheit", "Die vorgeschriebene Pausenlänge zwischen zwei Sätzen"],
                 correctAnswerIndex: 0,
                 explanation: "Periodisierung plant Trainingsreize systematisch über Wochen und Monate, um Fortschritt zu ermöglichen und Übertraining zu vermeiden."),
        Question(category: .trainingslehre, difficulty: .mittel,
                 text: "Was ist „Superkompensation“?",
                 answers: ["Die Phase nach der Erholung, in der die Leistungsfähigkeit über das Ausgangsniveau steigt", "Ein zusätzliches, besonders intensives Aufwärmprogramm vor dem Training", "Die maximale Muskelspannung, die während eines einzelnen Satzes erreicht wird", "Ein häufig eingesetztes Nahrungsergänzungsmittel für Kraftsportler"],
                 correctAnswerIndex: 0,
                 explanation: "Nach einer Trainingsbelastung und ausreichender Erholung steigt die Leistungsfähigkeit für eine gewisse Zeit über das vorherige Niveau – dieses Prinzip heißt Superkompensation."),
        Question(category: .trainingslehre, difficulty: .mittel,
                 text: "Was misst die RPE-Skala (Rate of Perceived Exertion)?",
                 answers: ["Die subjektiv empfundene Anstrengungsintensität", "Die Herzfrequenz in Schlägen pro Minute", "Das gehobene Gewicht in Kilogramm", "Die Trainingsdauer in Minuten"],
                 correctAnswerIndex: 0,
                 explanation: "Die RPE-Skala bewertet, wie anstrengend sich ein Satz subjektiv anfühlt, meist auf einer Skala von 1 bis 10."),
        // Schwer
        Question(category: .trainingslehre, difficulty: .schwer,
                 text: "Was unterscheidet ein lineares von einem undulierenden Periodisierungsmodell?",
                 answers: ["Lineares Modell steigert Intensität kontinuierlich über Wochen, undulierendes variiert sie häufiger", "Es gibt zwischen beiden Modellen praktisch keinen relevanten Unterschied", "Undulierend bedeutet, ausschließlich mit dem eigenen Körpergewicht zu trainieren", "Linear bezieht sich ausschließlich auf reines Ausdauertraining"],
                 correctAnswerIndex: 0,
                 explanation: "Lineare Periodisierung steigert die Intensität über Wochen kontinuierlich, während undulierende Periodisierung Intensität und Volumen häufiger – z.B. wöchentlich oder täglich – variiert."),
        Question(category: .trainingslehre, difficulty: .schwer,
                 text: "Welche zwei Reize gelten als Hauptmechanismen für Muskelhypertrophie?",
                 answers: ["Mechanische Spannung und metabolischer Stress", "Nur die Trainingsdauer", "Ausschließlich die Herzfrequenz", "Die Raumtemperatur beim Training"],
                 correctAnswerIndex: 0,
                 explanation: "Mechanische Spannung auf den Muskel und metabolischer Stress während des Trainings gelten als die zwei zentralen Reize für Muskelwachstum."),
        Question(category: .trainingslehre, difficulty: .schwer,
                 text: "Wie wird das Trainingsvolumen üblicherweise berechnet?",
                 answers: ["Sätze × Wiederholungen × Gewicht", "Nur die Anzahl der Trainingstage", "Trainingsdauer in Minuten", "Anzahl der genutzten Geräte"],
                 correctAnswerIndex: 0,
                 explanation: "Trainingsvolumen wird üblicherweise als Sätze mal Wiederholungen mal Gewicht berechnet und bildet die Gesamtbelastung einer Einheit ab."),
        Question(category: .trainingslehre, difficulty: .schwer,
                 text: "Was beschreibt das „Overtraining Syndrome“?",
                 answers: ["Chronische Leistungsminderung durch unzureichende Erholung im Verhältnis zur Belastung", "Eine einzelne, besonders harte und anstrengende Trainingseinheit", "Ein deutlich zu langes Aufwärmen direkt vor dem eigentlichen Training", "Ein dauerhaft zu geringes wöchentliches Trainingsvolumen"],
                 correctAnswerIndex: 0,
                 explanation: "Overtraining Syndrome entsteht, wenn Trainingsbelastung über längere Zeit die Erholungsfähigkeit übersteigt, und äußert sich in anhaltender Leistungsminderung."),
        Question(category: .trainingslehre, difficulty: .schwer,
                 text: "Wofür steht die „Repetition in Reserve“ (RIR)-Skala?",
                 answers: ["Wie viele Wiederholungen bis zum Muskelversagen noch möglich wären", "Wie viele Sätze noch im Programm übrig sind", "Wie viel Gewicht noch aufgelegt werden kann", "Wie lange die Pause noch dauert"],
                 correctAnswerIndex: 0,
                 explanation: "Die RIR-Skala gibt an, wie viele Wiederholungen bis zum Muskelversagen theoretisch noch möglich gewesen wären, und hilft, die Trainingsintensität zu steuern."),
    ]

    private static let ernaehrung: [Question] = [
        // Leicht
        Question(category: .ernaehrung, difficulty: .leicht,
                 text: "Welche drei Makronährstoffe liefern dem Körper Energie?",
                 answers: ["Kohlenhydrate, Fette, Proteine", "Vitamine, Mineralstoffe, Wasser", "Ballaststoffe, Wasser, Vitamine", "Nur Kohlenhydrate und Wasser"],
                 correctAnswerIndex: 0,
                 explanation: "Kohlenhydrate, Fette und Proteine liefern dem Körper Energie in Form von Kalorien.",
                 relatedTermSlug: "makronaehrstoffe"),
        Question(category: .ernaehrung, difficulty: .leicht,
                 text: "Wie viele Kalorien enthält 1 Gramm Kohlenhydrate ungefähr?",
                 answers: ["2 kcal", "4 kcal", "7 kcal", "9 kcal"],
                 correctAnswerIndex: 1,
                 explanation: "Kohlenhydrate liefern wie Proteine etwa 4 Kilokalorien pro Gramm.",
                 relatedTermSlug: "makronaehrstoffe"),
        Question(category: .ernaehrung, difficulty: .leicht,
                 text: "Wie viele Kalorien enthält 1 Gramm Fett ungefähr?",
                 answers: ["4 kcal", "7 kcal", "9 kcal", "12 kcal"],
                 correctAnswerIndex: 2,
                 explanation: "Fett liefert mit rund 9 Kilokalorien pro Gramm mehr als doppelt so viel Energie wie Kohlenhydrate oder Protein.",
                 relatedTermSlug: "makronaehrstoffe"),
        Question(category: .ernaehrung, difficulty: .leicht,
                 text: "Was ist der Hauptzweck von Protein in der Ernährung?",
                 answers: ["Baustoff für Muskeln und Gewebe", "Die einzige Energiequelle des Gehirns", "Schutz vor Sonnenbrand", "Beschleunigung der Verdauung von Fett"],
                 correctAnswerIndex: 0,
                 explanation: "Protein dient dem Körper vor allem als Baustoff für Muskeln, Organe und anderes Gewebe.",
                 relatedTermSlug: "proteinbedarf"),
        Question(category: .ernaehrung, difficulty: .leicht,
                 text: "Wie viel Wasser sollte ein Erwachsener ohne besondere Belastung täglich ungefähr trinken?",
                 answers: ["0,5 Liter", "1 Liter", "2–2,5 Liter", "5 Liter"],
                 correctAnswerIndex: 2,
                 explanation: "Für Erwachsene ohne besondere Belastung werden meist etwa 2 bis 2,5 Liter Flüssigkeit pro Tag empfohlen."),
        // Mittel
        Question(category: .ernaehrung, difficulty: .mittel,
                 text: "Was bedeutet ein „Kaloriendefizit“?",
                 answers: ["Man nimmt weniger Kalorien auf, als man verbraucht", "Man isst über den ganzen Tag verteilt nur noch Gemüse", "Man verzichtet in der Ernährung komplett auf Fett", "Man betreibt ausschließlich noch Ausdauertraining"],
                 correctAnswerIndex: 0,
                 explanation: "Ein Kaloriendefizit entsteht, wenn weniger Energie aufgenommen als verbraucht wird – die Grundvoraussetzung für Gewichtsabnahme.",
                 relatedTermSlug: "kalorienbilanz"),
        Question(category: .ernaehrung, difficulty: .mittel,
                 text: "Wie viel Protein pro Kilogramm Körpergewicht wird für Kraftsportler häufig empfohlen?",
                 answers: ["0,3–0,5 g/kg", "1,6–2,2 g/kg", "5–6 g/kg", "10 g/kg"],
                 correctAnswerIndex: 1,
                 explanation: "Für Kraftsportler werden häufig 1,6 bis 2,2 Gramm Protein pro Kilogramm Körpergewicht empfohlen, deutlich mehr als die allgemeine Empfehlung.",
                 relatedTermSlug: "proteinbedarf"),
        Question(category: .ernaehrung, difficulty: .mittel,
                 text: "Was beschreibt der glykämische Index eines Lebensmittels?",
                 answers: ["Wie schnell es den Blutzuckerspiegel erhöht", "Wie viele Kalorien es enthält", "Wie viel Wasser es enthält", "Wie lange es haltbar ist"],
                 correctAnswerIndex: 0,
                 explanation: "Der glykämische Index zeigt, wie stark und wie schnell ein Lebensmittel den Blutzuckerspiegel im Vergleich zu reiner Glukose ansteigen lässt.",
                 relatedTermSlug: "glykaemischer-index"),
        Question(category: .ernaehrung, difficulty: .mittel,
                 text: "Wie wichtig ist das sogenannte „anabole Fenster“ direkt nach dem Training nach aktuellem Kenntnisstand?",
                 answers: ["Entscheidender als die Gesamttagesmenge an Protein", "Weniger entscheidend als lange angenommen, Tagesmenge zählt mehr", "Es existiert wissenschaftlich nicht", "Nur bei Ausdauersport relevant"],
                 correctAnswerIndex: 1,
                 explanation: "Neuere Forschung zeigt, dass die über den Tag verteilte Gesamtproteinmenge wichtiger ist als ein kurzes Zeitfenster direkt nach dem Training.",
                 relatedTermSlug: "naehrstofftiming"),
        Question(category: .ernaehrung, difficulty: .mittel,
                 text: "Was versteht man unter „Nährstofftiming“?",
                 answers: ["Gezielte zeitliche Verteilung von Makronährstoffen rund ums Training", "Die Uhrzeit, zu der man gewöhnlich einkaufen geht", "Die Haltbarkeitsdauer von Lebensmitteln im Kühlschrank", "Die Reihenfolge der Zutaten auf der Verpackung"],
                 correctAnswerIndex: 0,
                 explanation: "Nährstofftiming beschreibt, wann Makronährstoffe – vor allem rund ums Training – gezielt aufgenommen werden.",
                 relatedTermSlug: "naehrstofftiming"),
        // Schwer
        Question(category: .ernaehrung, difficulty: .schwer,
                 text: "Was beschreibt der „Thermic Effect of Food“ (TEF)?",
                 answers: ["Die Energie, die der Körper für Verdauung/Verstoffwechselung aufwendet", "Wie warm eine Mahlzeit beim Servieren idealerweise sein sollte", "Den zusätzlichen Kaloriengehalt besonders scharfer Speisen", "Die Geschwindigkeit, mit der Wasser verdaut wird"],
                 correctAnswerIndex: 0,
                 explanation: "Der Thermic Effect of Food ist die Energie, die der Körper selbst für Verdauung und Verstoffwechselung der Nahrung verbraucht.",
                 relatedTermSlug: "tef"),
        Question(category: .ernaehrung, difficulty: .schwer,
                 text: "Was sind „essenzielle“ Aminosäuren?",
                 answers: ["Aminosäuren, die der Körper nicht selbst bilden kann und die über die Nahrung aufgenommen werden müssen", "Aminosäuren, die ausschließlich aus pflanzlichen Quellen stammen", "Aminosäuren, die ausschließlich dem Muskelaufbau dienen", "Aminosäuren, die der Körper nur während des Schlafs produziert"],
                 correctAnswerIndex: 0,
                 explanation: "Essenzielle Aminosäuren kann der Körper nicht selbst herstellen – sie müssen zwingend über die Nahrung aufgenommen werden.",
                 relatedTermSlug: "aminosaeuren"),
        Question(category: .ernaehrung, difficulty: .schwer,
                 text: "Was beschreibt die „Leucin-Schwelle“ für die Muskelproteinsynthese?",
                 answers: ["Die Menge Leucin, die pro Mahlzeit nötig ist, um eine maximale Syntheseantwort auszulösen", "Die maximale tägliche Fettaufnahme eines Kraftsportlers", "Den durchschnittlichen Blutzuckerwert direkt nach dem Training", "Die empfohlene Mindestmenge an Wasser pro Mahlzeit"],
                 correctAnswerIndex: 0,
                 explanation: "Die Leucin-Schwelle ist die Menge der Aminosäure Leucin pro Mahlzeit, die nötig ist, um die Muskelproteinsynthese maximal anzuregen.",
                 relatedTermSlug: "leucin-schwelle"),
        Question(category: .ernaehrung, difficulty: .schwer,
                 text: "Worin unterscheiden sich Kaloriendefizit und negative Stickstoffbilanz?",
                 answers: ["Kaloriendefizit betrifft die Energiebilanz, Stickstoffbilanz den Proteinauf-/-abbau", "Beide Begriffe beschreiben letztlich denselben Vorgang im Körper", "Die Stickstoffbilanz betrifft ausschließlich die Kohlenhydratzufuhr", "Ein Kaloriendefizit tritt ausschließlich bei Leistungssportlern auf"],
                 correctAnswerIndex: 0,
                 explanation: "Das Kaloriendefizit betrifft die Energiebilanz insgesamt, die Stickstoffbilanz speziell den Auf- und Abbau von Körperprotein.",
                 relatedTermSlug: "kalorienbilanz"),
        Question(category: .ernaehrung, difficulty: .schwer,
                 text: "Welche Rolle spielt Insulin im Nährstoffmetabolismus?",
                 answers: ["Anaboles Hormon, fördert Zellaufnahme von Glukose/Aminosäuren, hemmt Fettabbau", "Es baut im Körper ausschließlich Fettdepots ab", "Es hat auf den Stoffwechsel praktisch keinen Einfluss", "Es wird ausschließlich während körperlicher Belastung ausgeschüttet"],
                 correctAnswerIndex: 0,
                 explanation: "Insulin ist ein anaboles Hormon, das die Aufnahme von Glukose und Aminosäuren in die Zellen fördert und den Fettabbau hemmt.",
                 relatedTermSlug: "insulin"),
    ]

    private static let uebungsausfuehrung: [Question] = [
        // Leicht
        Question(category: .uebungsausfuehrung, difficulty: .leicht,
                 text: "Welche Muskelgruppe wird bei der klassischen Kniebeuge hauptsächlich beansprucht?",
                 answers: ["Quadrizeps und Gesäßmuskulatur", "Bizeps und vorderer Oberarm", "Wadenmuskulatur und Achillessehne", "Nacken- und Schultermuskulatur"],
                 correctAnswerIndex: 0,
                 explanation: "Die klassische Kniebeuge beansprucht primär den Quadrizeps (vordere Oberschenkelmuskulatur) sowie die Gesäßmuskulatur."),
        Question(category: .uebungsausfuehrung, difficulty: .leicht,
                 text: "In welche Richtung sollten die Knie bei einer korrekten Kniebeuge zeigen?",
                 answers: ["In Richtung der Fußspitzen", "Nach innen zusammen", "Nach außen weg von den Füßen", "Es spielt keine Rolle"],
                 correctAnswerIndex: 0,
                 explanation: "Die Knie sollten während der Kniebeuge etwa in Richtung der Fußspitzen zeigen, um die Gelenke gleichmäßig zu belasten."),
        Question(category: .uebungsausfuehrung, difficulty: .leicht,
                 text: "Was ist beim Liegestütz für die Körperhaltung wichtig?",
                 answers: ["Eine gerade Linie von Kopf bis Ferse", "Ein starkes Hohlkreuz", "Angehobenes Gesäß wie beim Berg", "Herabhängende Hüfte"],
                 correctAnswerIndex: 0,
                 explanation: "Eine gerade Linie von Kopf bis Ferse verhindert ein Durchhängen der Hüfte oder ein übermäßiges Hohlkreuz beim Liegestütz."),
        Question(category: .uebungsausfuehrung, difficulty: .leicht,
                 text: "Welche Muskelgruppe trainiert die klassische Plank (Unterarmstütz) hauptsächlich?",
                 answers: ["Die Rumpf-/Bauchmuskulatur", "Die Wadenmuskulatur", "Die Nackenmuskulatur", "Die Fingermuskulatur"],
                 correctAnswerIndex: 0,
                 explanation: "Die Plank trainiert vor allem die Rumpf- und Bauchmuskulatur, die den Körper in der stabilen Position hält."),
        Question(category: .uebungsausfuehrung, difficulty: .leicht,
                 text: "Was sollte man beim Heben von Gewichten vom Boden mit dem Rücken tun?",
                 answers: ["Den Rücken gerade halten, nicht rund werden lassen", "Den Rücken möglichst stark runden", "Den Kopf nach unten strecken", "Die Beine komplett durchstrecken lassen"],
                 correctAnswerIndex: 0,
                 explanation: "Ein gerader Rücken beim Heben verteilt die Last gleichmäßiger auf die Wirbelsäule und schützt vor Verletzungen."),
        // Mittel
        Question(category: .uebungsausfuehrung, difficulty: .mittel,
                 text: "Was ist beim Kreuzheben besonders wichtig, um den unteren Rücken zu schützen?",
                 answers: ["Eine neutrale Wirbelsäule halten und aus der Hüfte einleiten", "Den Rücken möglichst rund machen", "Die Stange möglichst weit vom Körper weg heben", "Die Knie komplett durchgestreckt lassen"],
                 correctAnswerIndex: 0,
                 explanation: "Eine neutrale Wirbelsäule und eine Bewegungseinleitung aus der Hüfte schützen den unteren Rücken beim Kreuzheben."),
        Question(category: .uebungsausfuehrung, difficulty: .mittel,
                 text: "Wo sollte die Stange beim Bankdrücken den Körper berühren?",
                 answers: ["Auf Höhe der unteren Brust/des Brustbeins", "Auf Höhe des Halses", "Auf Höhe des Bauchnabels", "Auf Höhe der Schultern"],
                 correctAnswerIndex: 0,
                 explanation: "Die Stange sollte beim Bankdrücken etwa auf Höhe der unteren Brust bzw. des Brustbeins den Körper berühren."),
        Question(category: .uebungsausfuehrung, difficulty: .mittel,
                 text: "Was beschreibt eine „exzentrische“ Muskelkontraktion?",
                 answers: ["Der Muskel verlängert sich unter Spannung", "Der Muskel verkürzt sich unter Spannung", "Der Muskel ist komplett entspannt", "Der Muskel zittert unkontrolliert"],
                 correctAnswerIndex: 0,
                 explanation: "Bei einer exzentrischen Kontraktion verlängert sich der Muskel, während er weiterhin Spannung aufbaut, z.B. beim Absenken in die Kniebeuge."),
        Question(category: .uebungsausfuehrung, difficulty: .mittel,
                 text: "Was beschreibt eine „konzentrische“ Muskelkontraktion?",
                 answers: ["Der Muskel verkürzt sich unter Spannung", "Der Muskel verlängert sich unter Spannung", "Der Muskel bleibt komplett passiv", "Der Muskel wird kälter"],
                 correctAnswerIndex: 0,
                 explanation: "Bei einer konzentrischen Kontraktion verkürzt sich der Muskel unter Spannung, z.B. beim Hochdrücken aus der Kniebeuge."),
        Question(category: .uebungsausfuehrung, difficulty: .mittel,
                 text: "Welche Fehlhaltung sollte man beim Überkopfdrücken besonders vermeiden?",
                 answers: ["Ein übermäßiges Hohlkreuz", "Zu langsames Ablegen der Hantel", "Zu lockere Schultern", "Zu enger Stand der Füße"],
                 correctAnswerIndex: 0,
                 explanation: "Ein übermäßiges Hohlkreuz beim Überkopfdrücken entlastet zwar kurzfristig die Schultern, belastet aber die untere Wirbelsäule unnötig."),
        // Schwer
        Question(category: .uebungsausfuehrung, difficulty: .schwer,
                 text: "Was unterscheidet „Low-Bar“ von „High-Bar“ Kniebeuge?",
                 answers: ["Die Stangenposition auf dem Rücken, was Oberkörperneigung und Muskelansteuerung beeinflusst", "Die Höhe der Hantelbank, auf der die Stange abgelegt wird", "Die Anzahl der Wiederholungen pro Satz bei dieser Übung", "Die Art der getragenen Trainingsschuhe während der Übung"],
                 correctAnswerIndex: 0,
                 explanation: "Die Stangenposition auf dem Rücken verändert die nötige Oberkörperneigung und damit, welche Muskeln stärker angesteuert werden."),
        Question(category: .uebungsausfuehrung, difficulty: .schwer,
                 text: "Welche Rolle spielt „Bracing“ beim Kreuzheben?",
                 answers: ["Aktives Anspannen der Rumpfmuskulatur zur Stabilisierung der Wirbelsäule", "Das Anlegen spezieller Bandagen an beiden Handgelenken", "Eine spezielle Atemtechnik, die nur die Beinmuskulatur betrifft", "Ein zusätzliches Aufwärmprogramm vor dem eigentlichen Satz"],
                 correctAnswerIndex: 0,
                 explanation: "Bracing ist das aktive Anspannen der Rumpfmuskulatur, um die Wirbelsäule während schwerer Hebungen wie dem Kreuzheben zu stabilisieren."),
        Question(category: .uebungsausfuehrung, difficulty: .schwer,
                 text: "Was versteht man unter dem „Sticking Point“ einer Kraftübung?",
                 answers: ["Den schwächsten, meist limitierenden Punkt in der Bewegungsbahn", "Den Startpunkt der Bewegung", "Die Position, an der die Übung beginnt zu schmerzen", "Den Punkt, an dem man die Hantel ablegt"],
                 correctAnswerIndex: 0,
                 explanation: "Der Sticking Point ist die schwächste Position in der Bewegungsbahn einer Übung und bestimmt oft, wie viel Gewicht insgesamt bewältigt werden kann."),
        Question(category: .uebungsausfuehrung, difficulty: .schwer,
                 text: "Warum wird beim Klimmzug eine „Scapula Depression/Retraction“ empfohlen?",
                 answers: ["Um die Schultern zu stabilisieren und die Zielmuskulatur effektiver anzusteuern", "Um die Übung schneller ausführen zu können", "Um weniger Wiederholungen schaffen zu müssen", "Um den Nacken zu entlasten und die Beine zu aktivieren"],
                 correctAnswerIndex: 0,
                 explanation: "Das Anspannen und Absenken der Schulterblätter stabilisiert die Schultern und lässt den Latissimus effektiver arbeiten."),
        Question(category: .uebungsausfuehrung, difficulty: .schwer,
                 text: "Was unterscheidet „Range of Motion“ (ROM) von „Time under Tension“ (TUT)?",
                 answers: ["ROM beschreibt die Bewegungsstrecke, TUT die Zeit unter Muskelspannung", "Beide beschreiben denselben Sachverhalt", "ROM misst die Zeit, TUT die Strecke", "TUT gilt nur für Ausdauertraining"],
                 correctAnswerIndex: 0,
                 explanation: "Range of Motion beschreibt die zurückgelegte Bewegungsstrecke, Time under Tension die Zeitdauer, die ein Muskel unter Spannung steht."),
    ]
}
