import Foundation

/// Static fitness-knowledge question catalog: 5 questions per
/// category/difficulty combination (3 categories × 3 difficulties × 5 = 45).
enum QuestionBank {
    static let all: [Question] = trainingslehre + ernaehrung + uebungsausfuehrung

    static func questions(for category: QuizCategory, difficulty: Difficulty) -> [Question] {
        all.filter { $0.category == category && $0.difficulty == difficulty }
    }

    private static let trainingslehre: [Question] = [
        // Leicht
        Question(category: .trainingslehre, difficulty: .leicht,
                 text: "Was bedeutet die Abkürzung „1RM“ im Krafttraining?",
                 answers: ["One-Repetition Maximum", "Resting Metabolic Rate", "Recovery Muscle Mass", "Range of Motion"],
                 correctAnswerIndex: 0),
        Question(category: .trainingslehre, difficulty: .leicht,
                 text: "Wie oft pro Woche empfiehlt die WHO mindestens muskelkräftigendes Training für Erwachsene?",
                 answers: ["1×", "2×", "4×", "7×"],
                 correctAnswerIndex: 1),
        Question(category: .trainingslehre, difficulty: .leicht,
                 text: "Was versteht man unter „Aufwärmen“ (Warm-up)?",
                 answers: ["Vorbereitende leichte Bewegung vor dem Training", "Ein Nickerchen vor dem Training", "Dehnen nach dem Training", "Eine kalte Dusche vor dem Training"],
                 correctAnswerIndex: 0),
        Question(category: .trainingslehre, difficulty: .leicht,
                 text: "Was ist eine „Wiederholung“ (Rep) beim Krafttraining?",
                 answers: ["Eine vollständige Ausführung einer Übung", "Eine Trainingswoche", "Eine Pause zwischen zwei Sätzen", "Ein komplettes Trainingsprogramm"],
                 correctAnswerIndex: 0),
        Question(category: .trainingslehre, difficulty: .leicht,
                 text: "Was bedeutet „Satz“ (Set) beim Krafttraining?",
                 answers: ["Eine Gruppe aufeinanderfolgender Wiederholungen ohne Pause", "Die maximale Gewichtsangabe", "Eine komplette Trainingswoche", "Der Name eines Übungsgeräts"],
                 correctAnswerIndex: 0),
        // Mittel
        Question(category: .trainingslehre, difficulty: .mittel,
                 text: "Was beschreibt das Prinzip der „progressiven Überlastung“?",
                 answers: ["Schrittweise Steigerung des Trainingsreizes zur Anpassung", "Immer dasselbe Gewicht über Monate zu nutzen", "Training bis zur völligen Erschöpfung in jeder Einheit", "Tägliches Training ohne Ruhetage"],
                 correctAnswerIndex: 0),
        Question(category: .trainingslehre, difficulty: .mittel,
                 text: "Wie lange sollte die Satzpause bei klassischem Hypertrophietraining (Muskelaufbau) typischerweise sein?",
                 answers: ["10–20 Sekunden", "60–90 Sekunden", "5 Minuten", "Keine Pause nötig"],
                 correctAnswerIndex: 1),
        Question(category: .trainingslehre, difficulty: .mittel,
                 text: "Was versteht man unter „Periodisierung“ im Training?",
                 answers: ["Systematische Planung und Variation von Trainingsreizen über die Zeit", "Das Zählen der Wiederholungen pro Satz", "Die Reihenfolge der Übungen in einer Einheit", "Die Pausenlänge zwischen Sätzen"],
                 correctAnswerIndex: 0),
        Question(category: .trainingslehre, difficulty: .mittel,
                 text: "Was ist „Superkompensation“?",
                 answers: ["Die Phase nach der Erholung, in der die Leistungsfähigkeit über das Ausgangsniveau steigt", "Ein zusätzliches Aufwärmprogramm", "Die maximale Muskelspannung während eines Satzes", "Ein Nahrungsergänzungsmittel"],
                 correctAnswerIndex: 0),
        Question(category: .trainingslehre, difficulty: .mittel,
                 text: "Was misst die RPE-Skala (Rate of Perceived Exertion)?",
                 answers: ["Die subjektiv empfundene Anstrengungsintensität", "Die Herzfrequenz in Schlägen pro Minute", "Das gehobene Gewicht in Kilogramm", "Die Trainingsdauer in Minuten"],
                 correctAnswerIndex: 0),
        // Schwer
        Question(category: .trainingslehre, difficulty: .schwer,
                 text: "Was unterscheidet ein lineares von einem undulierenden Periodisierungsmodell?",
                 answers: ["Lineares Modell steigert Intensität kontinuierlich über Wochen, undulierendes variiert sie häufiger", "Es gibt keinen Unterschied", "Undulierend heißt, nur mit Körpergewicht zu trainieren", "Linear bezieht sich nur auf Ausdauertraining"],
                 correctAnswerIndex: 0),
        Question(category: .trainingslehre, difficulty: .schwer,
                 text: "Welche zwei Reize gelten als Hauptmechanismen für Muskelhypertrophie?",
                 answers: ["Mechanische Spannung und metabolischer Stress", "Nur die Trainingsdauer", "Ausschließlich die Herzfrequenz", "Die Raumtemperatur beim Training"],
                 correctAnswerIndex: 0),
        Question(category: .trainingslehre, difficulty: .schwer,
                 text: "Wie wird das Trainingsvolumen üblicherweise berechnet?",
                 answers: ["Sätze × Wiederholungen × Gewicht", "Nur die Anzahl der Trainingstage", "Trainingsdauer in Minuten", "Anzahl der genutzten Geräte"],
                 correctAnswerIndex: 0),
        Question(category: .trainingslehre, difficulty: .schwer,
                 text: "Was beschreibt das „Overtraining Syndrome“?",
                 answers: ["Chronische Leistungsminderung durch unzureichende Erholung im Verhältnis zur Belastung", "Eine einzelne besonders harte Trainingseinheit", "Zu langes Aufwärmen vor dem Training", "Ein zu geringes Trainingsvolumen"],
                 correctAnswerIndex: 0),
        Question(category: .trainingslehre, difficulty: .schwer,
                 text: "Wofür steht die „Repetition in Reserve“ (RIR)-Skala?",
                 answers: ["Wie viele Wiederholungen bis zum Muskelversagen noch möglich wären", "Wie viele Sätze noch im Programm übrig sind", "Wie viel Gewicht noch aufgelegt werden kann", "Wie lange die Pause noch dauert"],
                 correctAnswerIndex: 0),
    ]

    private static let ernaehrung: [Question] = [
        // Leicht
        Question(category: .ernaehrung, difficulty: .leicht,
                 text: "Welche drei Makronährstoffe liefern dem Körper Energie?",
                 answers: ["Kohlenhydrate, Fette, Proteine", "Vitamine, Mineralstoffe, Wasser", "Ballaststoffe, Wasser, Vitamine", "Nur Kohlenhydrate und Wasser"],
                 correctAnswerIndex: 0),
        Question(category: .ernaehrung, difficulty: .leicht,
                 text: "Wie viele Kalorien enthält 1 Gramm Kohlenhydrate ungefähr?",
                 answers: ["2 kcal", "4 kcal", "7 kcal", "9 kcal"],
                 correctAnswerIndex: 1),
        Question(category: .ernaehrung, difficulty: .leicht,
                 text: "Wie viele Kalorien enthält 1 Gramm Fett ungefähr?",
                 answers: ["4 kcal", "7 kcal", "9 kcal", "12 kcal"],
                 correctAnswerIndex: 2),
        Question(category: .ernaehrung, difficulty: .leicht,
                 text: "Was ist der Hauptzweck von Protein in der Ernährung?",
                 answers: ["Baustoff für Muskeln und Gewebe", "Die einzige Energiequelle des Gehirns", "Schutz vor Sonnenbrand", "Beschleunigung der Verdauung von Fett"],
                 correctAnswerIndex: 0),
        Question(category: .ernaehrung, difficulty: .leicht,
                 text: "Wie viel Wasser sollte ein Erwachsener ohne besondere Belastung täglich ungefähr trinken?",
                 answers: ["0,5 Liter", "1 Liter", "2–2,5 Liter", "5 Liter"],
                 correctAnswerIndex: 2),
        // Mittel
        Question(category: .ernaehrung, difficulty: .mittel,
                 text: "Was bedeutet ein „Kaloriendefizit“?",
                 answers: ["Man nimmt weniger Kalorien auf, als man verbraucht", "Man isst nur noch Gemüse", "Man verzichtet komplett auf Fett", "Man trainiert nur noch Ausdauer"],
                 correctAnswerIndex: 0),
        Question(category: .ernaehrung, difficulty: .mittel,
                 text: "Wie viel Protein pro Kilogramm Körpergewicht wird für Kraftsportler häufig empfohlen?",
                 answers: ["0,3–0,5 g/kg", "1,6–2,2 g/kg", "5–6 g/kg", "10 g/kg"],
                 correctAnswerIndex: 1),
        Question(category: .ernaehrung, difficulty: .mittel,
                 text: "Was beschreibt der glykämische Index eines Lebensmittels?",
                 answers: ["Wie schnell es den Blutzuckerspiegel erhöht", "Wie viele Kalorien es enthält", "Wie viel Wasser es enthält", "Wie lange es haltbar ist"],
                 correctAnswerIndex: 0),
        Question(category: .ernaehrung, difficulty: .mittel,
                 text: "Wie wichtig ist das sogenannte „anabole Fenster“ direkt nach dem Training nach aktuellem Kenntnisstand?",
                 answers: ["Entscheidender als die Gesamttagesmenge an Protein", "Weniger entscheidend als lange angenommen, Tagesmenge zählt mehr", "Es existiert wissenschaftlich nicht", "Nur bei Ausdauersport relevant"],
                 correctAnswerIndex: 1),
        Question(category: .ernaehrung, difficulty: .mittel,
                 text: "Was versteht man unter „Nährstofftiming“?",
                 answers: ["Gezielte zeitliche Verteilung von Makronährstoffen rund ums Training", "Die Uhrzeit, zu der man einkaufen geht", "Die Haltbarkeitsdauer von Lebensmitteln", "Die Reihenfolge der Zutaten auf der Verpackung"],
                 correctAnswerIndex: 0),
        // Schwer
        Question(category: .ernaehrung, difficulty: .schwer,
                 text: "Was beschreibt der „Thermic Effect of Food“ (TEF)?",
                 answers: ["Die Energie, die der Körper für Verdauung/Verstoffwechselung aufwendet", "Wie warm eine Mahlzeit serviert werden sollte", "Den Kaloriengehalt scharfer Speisen", "Die Verdauungsgeschwindigkeit von Wasser"],
                 correctAnswerIndex: 0),
        Question(category: .ernaehrung, difficulty: .schwer,
                 text: "Was sind „essenzielle“ Aminosäuren?",
                 answers: ["Solche, die der Körper nicht selbst herstellen kann und die über die Nahrung aufgenommen werden müssen", "Nur pflanzliche Aminosäuren", "Aminosäuren, die ausschließlich Muskeln aufbauen", "Aminosäuren, die nur im Schlaf produziert werden"],
                 correctAnswerIndex: 0),
        Question(category: .ernaehrung, difficulty: .schwer,
                 text: "Was beschreibt die „Leucin-Schwelle“ für die Muskelproteinsynthese?",
                 answers: ["Die Menge Leucin, die pro Mahlzeit nötig ist, um eine maximale Syntheseantwort auszulösen", "Die maximale tägliche Fettaufnahme", "Den Blutzuckerwert nach dem Training", "Die Mindestmenge an Wasser pro Mahlzeit"],
                 correctAnswerIndex: 0),
        Question(category: .ernaehrung, difficulty: .schwer,
                 text: "Worin unterscheiden sich Kaloriendefizit und negative Stickstoffbilanz?",
                 answers: ["Kaloriendefizit betrifft die Energiebilanz, Stickstoffbilanz den Proteinauf-/-abbau", "Beide beschreiben denselben Vorgang", "Stickstoffbilanz betrifft nur Kohlenhydrate", "Kaloriendefizit gibt es nur bei Sportlern"],
                 correctAnswerIndex: 0),
        Question(category: .ernaehrung, difficulty: .schwer,
                 text: "Welche Rolle spielt Insulin im Nährstoffmetabolismus?",
                 answers: ["Anaboles Hormon, fördert Zellaufnahme von Glukose/Aminosäuren, hemmt Fettabbau", "Es baut ausschließlich Fett ab", "Es hat keinen Einfluss auf den Stoffwechsel", "Es wird nur beim Sport ausgeschüttet"],
                 correctAnswerIndex: 0),
    ]

    private static let uebungsausfuehrung: [Question] = [
        // Leicht
        Question(category: .uebungsausfuehrung, difficulty: .leicht,
                 text: "Welche Muskelgruppe wird bei der klassischen Kniebeuge hauptsächlich beansprucht?",
                 answers: ["Quadrizeps und Gesäßmuskulatur", "Bizeps", "Wadenmuskulatur allein", "Nackenmuskulatur"],
                 correctAnswerIndex: 0),
        Question(category: .uebungsausfuehrung, difficulty: .leicht,
                 text: "In welche Richtung sollten die Knie bei einer korrekten Kniebeuge zeigen?",
                 answers: ["In Richtung der Fußspitzen", "Nach innen zusammen", "Nach außen weg von den Füßen", "Es spielt keine Rolle"],
                 correctAnswerIndex: 0),
        Question(category: .uebungsausfuehrung, difficulty: .leicht,
                 text: "Was ist beim Liegestütz für die Körperhaltung wichtig?",
                 answers: ["Eine gerade Linie von Kopf bis Ferse", "Ein starkes Hohlkreuz", "Angehobenes Gesäß wie beim Berg", "Herabhängende Hüfte"],
                 correctAnswerIndex: 0),
        Question(category: .uebungsausfuehrung, difficulty: .leicht,
                 text: "Welche Muskelgruppe trainiert die klassische Plank (Unterarmstütz) hauptsächlich?",
                 answers: ["Die Rumpf-/Bauchmuskulatur", "Die Wadenmuskulatur", "Die Nackenmuskulatur", "Die Fingermuskulatur"],
                 correctAnswerIndex: 0),
        Question(category: .uebungsausfuehrung, difficulty: .leicht,
                 text: "Was sollte man beim Heben von Gewichten vom Boden mit dem Rücken tun?",
                 answers: ["Den Rücken gerade halten, nicht rund werden lassen", "Den Rücken möglichst stark runden", "Den Kopf nach unten strecken", "Die Beine komplett durchstrecken lassen"],
                 correctAnswerIndex: 0),
        // Mittel
        Question(category: .uebungsausfuehrung, difficulty: .mittel,
                 text: "Was ist beim Kreuzheben besonders wichtig, um den unteren Rücken zu schützen?",
                 answers: ["Eine neutrale Wirbelsäule halten und aus der Hüfte einleiten", "Den Rücken möglichst rund machen", "Die Stange möglichst weit vom Körper weg heben", "Die Knie komplett durchgestreckt lassen"],
                 correctAnswerIndex: 0),
        Question(category: .uebungsausfuehrung, difficulty: .mittel,
                 text: "Wo sollte die Stange beim Bankdrücken den Körper berühren?",
                 answers: ["Auf Höhe der unteren Brust/des Brustbeins", "Auf Höhe des Halses", "Auf Höhe des Bauchnabels", "Auf Höhe der Schultern"],
                 correctAnswerIndex: 0),
        Question(category: .uebungsausfuehrung, difficulty: .mittel,
                 text: "Was beschreibt eine „exzentrische“ Muskelkontraktion?",
                 answers: ["Der Muskel verlängert sich unter Spannung", "Der Muskel verkürzt sich unter Spannung", "Der Muskel ist komplett entspannt", "Der Muskel zittert unkontrolliert"],
                 correctAnswerIndex: 0),
        Question(category: .uebungsausfuehrung, difficulty: .mittel,
                 text: "Was beschreibt eine „konzentrische“ Muskelkontraktion?",
                 answers: ["Der Muskel verkürzt sich unter Spannung", "Der Muskel verlängert sich unter Spannung", "Der Muskel bleibt komplett passiv", "Der Muskel wird kälter"],
                 correctAnswerIndex: 0),
        Question(category: .uebungsausfuehrung, difficulty: .mittel,
                 text: "Welche Fehlhaltung sollte man beim Überkopfdrücken besonders vermeiden?",
                 answers: ["Ein übermäßiges Hohlkreuz", "Zu langsames Ablegen der Hantel", "Zu lockere Schultern", "Zu enger Stand der Füße"],
                 correctAnswerIndex: 0),
        // Schwer
        Question(category: .uebungsausfuehrung, difficulty: .schwer,
                 text: "Was unterscheidet „Low-Bar“ von „High-Bar“ Kniebeuge?",
                 answers: ["Die Stangenposition auf dem Rücken, was Oberkörperneigung und Muskelansteuerung beeinflusst", "Die Höhe der Hantelbank", "Die Anzahl der Wiederholungen", "Die Trainingsschuhe"],
                 correctAnswerIndex: 0),
        Question(category: .uebungsausfuehrung, difficulty: .schwer,
                 text: "Welche Rolle spielt „Bracing“ beim Kreuzheben?",
                 answers: ["Aktives Anspannen der Rumpfmuskulatur zur Stabilisierung der Wirbelsäule", "Das Anlegen von Handgelenksbandagen", "Eine spezielle Atemtechnik nur für die Beine", "Ein zusätzliches Aufwärmprogramm"],
                 correctAnswerIndex: 0),
        Question(category: .uebungsausfuehrung, difficulty: .schwer,
                 text: "Was versteht man unter dem „Sticking Point“ einer Kraftübung?",
                 answers: ["Den schwächsten, meist limitierenden Punkt in der Bewegungsbahn", "Den Startpunkt der Bewegung", "Die Position, an der die Übung beginnt zu schmerzen", "Den Punkt, an dem man die Hantel ablegt"],
                 correctAnswerIndex: 0),
        Question(category: .uebungsausfuehrung, difficulty: .schwer,
                 text: "Warum wird beim Klimmzug eine „Scapula Depression/Retraction“ empfohlen?",
                 answers: ["Um die Schultern zu stabilisieren und die Zielmuskulatur effektiver anzusteuern", "Um die Übung schneller ausführen zu können", "Um weniger Wiederholungen schaffen zu müssen", "Um den Nacken zu entlasten und die Beine zu aktivieren"],
                 correctAnswerIndex: 0),
        Question(category: .uebungsausfuehrung, difficulty: .schwer,
                 text: "Was unterscheidet „Range of Motion“ (ROM) von „Time under Tension“ (TUT)?",
                 answers: ["ROM beschreibt die Bewegungsstrecke, TUT die Zeit unter Muskelspannung", "Beide beschreiben denselben Sachverhalt", "ROM misst die Zeit, TUT die Strecke", "TUT gilt nur für Ausdauertraining"],
                 correctAnswerIndex: 0),
    ]
}
